const EVENTS = {
    PIPELINE_CREATED: "PIPELINE_CREATED",
    PIPELINE_UPDATED: "PIPELINE_UPDATED",

    AGENT_STARTED: "AGENT_STARTED",
    AGENT_FINISHED: "AGENT_FINISHED",

    TASK_STARTED: "TASK_STARTED",
    TASK_FINISHED: "TASK_FINISHED",

    WAITING_APPROVAL: "WAITING_APPROVAL",

    EXECUTION_COMPLETE: "EXECUTION_COMPLETE"
};

module.exports = EVENTS;